폴더 잘못 올려 수정합니다
DSC-University-of-Seoul/2021-spring-web pull request #32
Opened 2021-05-16 11:25 UTC by yuniwisdom

2021-05-17 11:35 UTC, edit8080 requested changes
Lint 에러를 해결해주세요.

2021-05-17 11:35 UTC, edit8080 commented on May_Week_2/yuniwisdom_choiyoonji(beginner).md
> +>* 도시이름을 누르면 하위 리스트 열고 닫히는 토글기능(javascript-함수 이용)
a태그의 href 속성을 통해 javascript:동작함수 형태로도 클릭 이벤트를 구현할 수 있다는 사실을 처음알았네요.
나중에는 이벤트 핸들링을 통한 방법도 찾아보시면 좋을것 같아요!!

2021-05-18 08:27 UTC, edit8080 commented
여전히 lint 에러가 발생하고 있네요 ㅜㅜ
하단에서 All checkes have failed 오류가 뜨는 것을 고쳐주세요

2021-05-18 13:31 UTC, yuniwisdom commented
lint 수정이 어떻게 하는거죠ㅜㅜ해결방법을 모르겠습니다..

2021-05-18 13:56 UTC, edit8080 commented
https://github.com/DSC-University-of-Seoul/2021-spring-web/blob/main/CONTRIBUTING.md

이 문서를 참고해주세요 😃

2021-05-19 14:05 UTC, yuniwisdom commented
수정 완료했습니다!!

2021-05-22 11:31 UTC, edit8080 approved these changes

2021-05-22 11:31 UTC, merged